services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=retrospect
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d retrospect"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - DB_SOURCE=postgresql://root:root@postgres:5432/retrospect?sslmode=disable
      - GIN_MODE=release
    depends_on:
      postgres:
        condition: service_healthy
