// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Challenge struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	UserID      uuid.UUID      `json:"user_id"`
	Description sql.NullString `json:"description"`
	StartDate   time.Time      `json:"start_date"`
	EndDate     sql.NullTime   `json:"end_date"`
	Active      sql.NullBool   `json:"active"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ChallengeEntry struct {
	ID          uuid.UUID    `json:"id"`
	ChallengeID uuid.UUID    `json:"challenge_id"`
	Date        sql.NullTime `json:"date"`
	Completed   sql.NullBool `json:"completed"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type CurrentChallengesView struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	UserID      uuid.UUID      `json:"user_id"`
	Description sql.NullString `json:"description"`
	StartDate   time.Time      `json:"start_date"`
	EndDate     sql.NullTime   `json:"end_date"`
	Active      sql.NullBool   `json:"active"`
	CreatedAt   time.Time      `json:"created_at"`
	Duration    interface{}    `json:"duration"`
}

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}

type Task struct {
	ID          uuid.UUID      `json:"id"`
	TaskDayID   uuid.UUID      `json:"task_day_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Duration    int64          `json:"duration"`
	Completed   sql.NullBool   `json:"completed"`
}

type TaskDay struct {
	ID            uuid.UUID     `json:"id"`
	UserID        uuid.UUID     `json:"user_id"`
	Date          sql.NullTime  `json:"date"`
	Count         sql.NullInt32 `json:"count"`
	TotalDuration sql.NullInt64 `json:"total_duration"`
}

type User struct {
	ID        uuid.UUID    `json:"id"`
	Email     string       `json:"email"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	Timezone  string       `json:"timezone"`
}
