// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email, name, hashed_password
) VALUES (
  $1, $2, $3
)
RETURNING id, email, name, created_at, updated_at, timezone, password_changed_at, hashed_password, is_verified
`

type CreateUserParams struct {
	Email          string `json:"email"`
	Name           string `json:"name"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.PasswordChangedAt,
		&i.HashedPassword,
		&i.IsVerified,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id, email, name, created_at, updated_at, timezone, password_changed_at, hashed_password, is_verified
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.PasswordChangedAt,
		&i.HashedPassword,
		&i.IsVerified,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, created_at, updated_at, timezone, password_changed_at, hashed_password, is_verified FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.PasswordChangedAt,
		&i.HashedPassword,
		&i.IsVerified,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, email, name, created_at, updated_at, timezone, password_changed_at, hashed_password, is_verified FROM users 
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.PasswordChangedAt,
		&i.HashedPassword,
		&i.IsVerified,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, created_at, updated_at, timezone, password_changed_at, hashed_password, is_verified FROM users
ORDER BY name
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Timezone,
			&i.PasswordChangedAt,
			&i.HashedPassword,
			&i.IsVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET
  email = $2,
  updated_at = NOW()
WHERE
  id = $1
RETURNING id, email, name, created_at, updated_at, timezone, password_changed_at, hashed_password, is_verified
`

type UpdateUserEmailParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.PasswordChangedAt,
		&i.HashedPassword,
		&i.IsVerified,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET
  name = $2,
  updated_at = NOW()
WHERE
  id = $1
RETURNING id, email, name, created_at, updated_at, timezone, password_changed_at, hashed_password, is_verified
`

type UpdateUserNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.PasswordChangedAt,
		&i.HashedPassword,
		&i.IsVerified,
	)
	return i, err
}

const updateUserTimezone = `-- name: UpdateUserTimezone :one
UPDATE users
SET
  timezone = $2,
  updated_at = NOW()
WHERE
  id = $1
RETURNING id, email, name, created_at, updated_at, timezone, password_changed_at, hashed_password, is_verified
`

type UpdateUserTimezoneParams struct {
	ID       pgtype.UUID `json:"id"`
	Timezone string      `json:"timezone"`
}

func (q *Queries) UpdateUserTimezone(ctx context.Context, arg UpdateUserTimezoneParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTimezone, arg.ID, arg.Timezone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.PasswordChangedAt,
		&i.HashedPassword,
		&i.IsVerified,
	)
	return i, err
}
