// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sanjayj369/retrospect-backend/mail (interfaces: EmailSender)
//
// Generated by this command:
//
//	mockgen -package mockmail -destination mail/mock/sender.go github.com/sanjayj369/retrospect-backend/mail EmailSender
//

// Package mockmail is a generated GoMock package.
package mockmail

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
	isgomock struct{}
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// SendMail mocks base method.
func (m *MockEmailSender) SendMail(subject, content string, to, cc, bcc, attachFiles []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMail", subject, content, to, cc, bcc, attachFiles)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMail indicates an expected call of SendMail.
func (mr *MockEmailSenderMockRecorder) SendMail(subject, content, to, cc, bcc, attachFiles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMail", reflect.TypeOf((*MockEmailSender)(nil).SendMail), subject, content, to, cc, bcc, attachFiles)
}
